### ISSUE TITLE
Normalize custom module attribute names; keep custom type definitions

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-representer#24]
Make sure that custom module attributes get their names replaced by placeholders, but module attributes that define custom types (https://hexdocs.pm/elixir/typespecs.html#types-and-their-syntax) remain unchanged. Make sure that the usages of the custom module attributes us the same attribute placeholder.

## Example input:
```elixir
defmodule HelloWorld do
  @type custom_integer :: integer
  @some_module_attribute 8

  # Comment
  @spec add_then_subtract(custom_integer(), integer(), integer()) :: integer()
  def add_then_subtract(n, a, s) do
    total = n+a
    total - s
  end
end
```

## Desired output:
```elixir
defmodule(PLACEHOLDER_1) do
  @type(custom_integer() :: integer())
  @PLACEHOLDER_2(8)
  @spec(add_then_subtract(custom_integer(), integer(), integer()) :: integer())
  def(PLACEHOLDER_4(PLACEHOLDER_5, PLACEHOLDER_6, PLACEHOLDER_7)) do
    PLACEHOLDER_8 = PLACEHOLDER_5 + PLACEHOLDER_6
    PLACEHOLDER_8 - PLACEHOLDER_7
  end
end
```
(please ignore missing PLACEHOLDER_3)

## Current output:
```elixir
defmodule(PLACEHOLDER_1) do
  @type(PLACEHOLDER_2 :: PLACEHOLDER_3)
  @some_module_attribute(8)
  @spec(add_then_subtract(custom_integer(), integer(), integer()) :: integer())
  def(PLACEHOLDER_4(PLACEHOLDER_5, PLACEHOLDER_6, PLACEHOLDER_7)) do
    PLACEHOLDER_8 = PLACEHOLDER_5 + PLACEHOLDER_6
    PLACEHOLDER_8 - PLACEHOLDER_7
  end
end
```

**Comment by jiegillet** [comment]
I would expect `@type custom_integer :: integer` to be normalized as `@type(PLACEHOLDER_1 :: integer)`. Why do we treat a custom type name differently?

**Comment by angelikatyborska** [comment]
I'm not sure why I wrote the ticket like that. Maybe out of laziness not to have to replace the names in typespecs?

So you're saying this input:
```elixir
defmodule HelloWorld do
  @type custom_integer :: integer
  @some_module_attribute 8

  # Comment
  @spec add_then_subtract(custom_integer(), integer(), integer()) :: integer()
  def add_then_subtract(n, a, s) do
    total = n+a
    total - s
  end
end
```

Should become:
```elixir
defmodule(PLACEHOLDER_1) do
  @type(PLACEHOLDER_2 :: integer())
  @PLACEHOLDER_2(8)
  @spec(PLACEHOLDER_4(PLACEHOLDER_2, integer(), integer()) :: integer())
  def(PLACEHOLDER_4(PLACEHOLDER_5, PLACEHOLDER_6, PLACEHOLDER_7)) do
    PLACEHOLDER_8 = PLACEHOLDER_5 + PLACEHOLDER_6
    PLACEHOLDER_8 - PLACEHOLDER_7
  end
end
```
?

**Comment by jiegillet** [comment]
Yep, that's what I'm thinking.

**Comment by jiegillet** [comment]
Follow up question I just had. Fore the following code
```elixir
@spec id(integer :: integer()) :: integer()
def id(integer), do: integer
```
There is a name shadowing between the variable name and the type. I know it is important that same names are represented the same way, but this case is a bit strange.

### Representation 1: not represented the same way
```elixir
@spec placeholder_1(placeholder_2 :: integer()) :: integer()
def placeholder_1(placeholder_2), do: placeholder_2
```

### Representation 2: keeping `integer`
```elixir
@spec placeholder_1(integer :: integer()) :: integer()
def placeholder_1(integer), do: integer
```

### Representation 3: replacing type as well
```elixir
@spec placeholder_1(placeholder_2 :: placeholder_2()) :: placeholder_2()
def placeholder_1(placeholder_2), do: placeholder_2
```

None of them seem perfectly right. 
1 should be avoided because we cannot comment on the shadowing (although TBH shadowing a type is not a problem because they cannot interact)
2 feels like the representer has a bug, or that we have type-level functions
3 feels like integer is a custom type

In 5 minutes I've changed my mind 4 times over which I prefer.

**Comment by angelikatyborska** [comment]
> although TBH shadowing a type is not a problem because they cannot interact

It's not even "shadowing". It's clear from context with one is a variable, and which one is a type. It's perfectly fine to name your arguments the same as a type. As I said on Slack already, my vote is for option 1.

For type names, only custom type names could be replaced by placeholders, and I guess using the same logic as for module names - if the type is being defined in this module (or in the solution in general?), use a placeholder. Otherwise keep the original name.
