### ISSUE TITLE
Sort arguments for symmetric functions

### ISSUE THREAD

**Issue by jiegillet** [exercism/elixir-representer#35]
If someone calls `a+b` and someone else calls `b+a`, they should be represented by the same thing.
Operators that are symmetric include: `Kernel.+/2`, `Kernel.*/2`, `Kernel.==/2`, `Kernel.===/2`, `Kernel.!=/2`, `Kernel.!==/2`, `Kernel.max/2`, `Kernel.min/2`, `Integer.gcd/2`, `Integer.extended_gcd/2`...

Caution: some operators like `or` and `and` may seem symmetric, but they are not because they are lazy: `true or (raise "woops") == true`.

## Example input 

```elixir
def calc1(a, b, c), do: a + b * c
def calc2(a, b, c), do: a + c * b
def calc3(a, b, c), do: b * c + a
def calc4(a, b, c), do: c * d + a
```
## Desired output

```elixir
  def(PLACEHOLDER_1(PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER_4)) do
    PLACEHOLDER_2 + PLACEHOLDER_3 * PLACEHOLDER_4
  end
  def(PLACEHOLDER_5(PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER_4)) do
    PLACEHOLDER_2 + PLACEHOLDER_3 * PLACEHOLDER_4
  end
  def(PLACEHOLDER_6(PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER_4)) do
    PLACEHOLDER_2 + PLACEHOLDER_3 * PLACEHOLDER_4
  end
  def(PLACEHOLDER_7(PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER_4)) do
    PLACEHOLDER_2 + PLACEHOLDER_3 * PLACEHOLDER_4
  end
```
The order of the placeholders doesn't really matter as long as it's consistent. Probably the simplest way is to use `Enum.sort` on the arguments of the symmetric operators.

## Current output

```elixir
  def(PLACEHOLDER_1(PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER_4)) do
    PLACEHOLDER_2 + PLACEHOLDER_3 * PLACEHOLDER_4
  end
  def(PLACEHOLDER_5(PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER_4)) do
    PLACEHOLDER_2 + PLACEHOLDER_4 * PLACEHOLDER_3
  end
  def(PLACEHOLDER_6(PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER_4)) do
    PLACEHOLDER_3 * PLACEHOLDER_4 + PLACEHOLDER_2
  end
  def(PLACEHOLDER_7(PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER_4)) do
    PLACEHOLDER_4 * PLACEHOLDER_3 + PLACEHOLDER_2
  end
```

**Comment by angelikatyborska** [comment]
I think it makes sense, although it wouldn't be my highest priority to do in this project.

I wonder if there are any hidden gotchas here. I think as long as we correctly identify which functions are symmetric and which not, it should be safe. I'll still ask around what other languages think about this.

**Comment by jiegillet** [comment]
Sounds good.
And yes, I've already identified a gotcha, so there might be more. I thought of looking at the function implementations, but I'm sure most of these end up in Erlang don't know Erlang yet :)

**Comment by jiegillet** [comment]
After discussions on Slack (ages ago), I think we reached the conclusion that that behavior is not desirable, because sometimes the order does matter. 
For example:
- in tests, the expected output is usually on the right hand side
- in a math calculation, it might be clearer to arrange the terms in a particular way that is standard or something
- for readability, people might choose to write terms in a way that give out a cleaner formatted output

So I'm closing this proposal :)
