### ISSUE TITLE
Work to be done

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir-representer#4]
- [ ] needs docker deployment
- representer work:
  - [x] regress the representer to these steps:
     - [x] remove the comments
     - [x] walk the ast
       - if a name is found (variable, module, function), replace with a placeholder, keep track of it.
     - [x] output the ast as the 'represented' format

**Comment by ErikSchierboom** [comment]
I would also suggest building the Docker image in CI and then running that built image on some test output to verify that the Docker image that is produced is valid.
