### ISSUE TITLE
Dockerhub problem

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir-representer#8]
see exercism/elixir-analyzer#22 for the same error.  CI fails for this repo, but succeeds for exercism/elixir-test-runner.  Unsure why.

@erikschierboom, did I miss something here too?

**Comment by ErikSchierboom** [comment]
See https://github.com/exercism/elixir-analyzer/issues/22#issuecomment-693218025

**Comment by neenjaw** [comment]
¯\\\_(ツ)\_/¯
